# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, default='', max_length=100)),
                ('times', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ('price',),
            },
        ),
    ]
